# Generated by Django 6.0.3 on 2026-03-16 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工厂名称')),
                ('location', models.CharField(max_length=100, verbose_name='地区')),
                ('workshop', models.CharField(max_length=50, verbose_name='车间')),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('辅料', '辅料'), ('面料', '面料')], max_length=10, verbose_name='原料类型')),
                ('name', models.CharField(max_length=100, verbose_name='原料名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('stock_date', models.DateField(verbose_name='入库日期')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('size', models.CharField(max_length=20, verbose_name='尺码')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.factory', verbose_name='工厂')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.material', verbose_name='原料')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
                ('outbound_date', models.DateField(verbose_name='出库日期')),
                ('warehouse', models.CharField(max_length=100, verbose_name='仓库')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='计划数量')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('expected_end_date', models.DateField(verbose_name='预计结束日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
            },
        ),
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(verbose_name='当前数量')),
                ('status', models.CharField(choices=[('进行中', '进行中'), ('已完成', '已完成'), ('暂停', '暂停')], max_length=10, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionplan', verbose_name='生产计划')),
            ],
            options={
                'verbose_name': '生产进度',
                'verbose_name_plural': '生产进度',
            },
        ),
    ]
