# Generated by Django 6.0.3 on 2026-03-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('size', models.CharField(max_length=20, verbose_name='尺码')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.factory', verbose_name='工厂')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
    ]
