# Generated by Django 6.0.3 on 2026-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
    ]
