# Generated by Django 6.0.3 on 2026-03-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_warehouse_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='', max_length=200, verbose_name='颜色选项'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(default='', max_length=200, verbose_name='规格参数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='产品名称'),
        ),
    ]
