# Generated by Django 6.0.3 on 2026-03-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_product_factory_remove_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='产品'),
        ),
    ]
