# Generated by Django 6.0.3 on 2026-03-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_warehouse_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('type', models.CharField(choices=[('辅料', '辅料'), ('面料', '面料')], max_length=10, verbose_name='供应商类型')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='material_attachments/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='material',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.factory', verbose_name='目标工厂'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.supplier', verbose_name='供应商'),
        ),
    ]
