# Generated by Django 6.0.3 on 2026-03-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_supplier_material_attachment_material_factory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='计划日期')),
                ('plan_type', models.CharField(max_length=50, verbose_name='计划类型')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('template', models.CharField(max_length=50, verbose_name='模板类型')),
                ('models_data', models.JSONField(default=list, verbose_name='型号数据')),
                ('sizes_data', models.JSONField(default=list, verbose_name='尺码数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.factory', verbose_name='目标工厂')),
            ],
            options={
                'verbose_name': '生产计划明细',
                'verbose_name_plural': '生产计划明细',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
