# Generated by Django 6.0.3 on 2026-03-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productionplandetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundrecord',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='尺码'),
        ),
    ]
