# Generated by Django 6.0.4 on 2026-04-28 09:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_outboundrecord_color_outboundrecord_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '调拨单',
                'verbose_name_plural': '调拨单',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '物料库存', 'verbose_name_plural': '物料库存'},
        ),
        migrations.AlterModelOptions(
            name='outboundrecord',
            options={'verbose_name': '出库单', 'verbose_name_plural': '出库单'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': '成品库存', 'verbose_name_plural': '成品库存'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='factory',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='material',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='material',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.material', verbose_name='来源坯布'),
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='status',
            field=models.CharField(choices=[('completed', '已完成'), ('revoked', '已撤回')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('raw_fabric', '坯布'), ('dyed_fabric', '染色布'), ('accessory', '辅料')], max_length=20, verbose_name='物料类型'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('辅料', '辅料'), ('坯布', '坯布'), ('染厂', '染厂')], max_length=10, verbose_name='供应商类型'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.transferorder')),
            ],
            options={
                'verbose_name': '调拨单明细',
                'verbose_name_plural': '调拨单明细',
            },
        ),
        migrations.CreateModel(
            name='WarehouseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仓库名称')),
                ('warehouse_type', models.CharField(choices=[('factory', '工厂仓'), ('local', '本地仓')], max_length=20, verbose_name='仓库类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '仓库主数据',
                'verbose_name_plural': '仓库主数据',
            },
        ),
        migrations.AddField(
            model_name='transferorder',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from_orders', to='production.warehousenode'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to_orders', to='production.warehousenode'),
        ),
        migrations.CreateModel(
            name='DyeingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(max_length=100, verbose_name='染色布名称')),
                ('output_color', models.CharField(max_length=50, verbose_name='颜色')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dyed_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_dyeing_order', to='production.material')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_orders', to='production.material', verbose_name='坯布')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_orders', to='production.supplier', verbose_name='染厂')),
                ('output_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.warehousenode', verbose_name='入库仓')),
            ],
            options={
                'verbose_name': '染色单',
                'verbose_name_plural': '染色单',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.warehousenode', verbose_name='所属仓库'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production.warehousenode', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.warehousenode', verbose_name='出库仓'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('warehouse', 'product', 'color', 'size')},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='factory',
        ),
    ]
