# Generated by Django 4.2.30 on 2026-04-30 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_outboundrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='attachment',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='material_attachments/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'doc', 'docx', 'xlsx', 'xls']
                    )
                ],
                verbose_name='附件',
            ),
        ),
    ]
