# Generated by Django 4.2.30 on 2026-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_sync_model_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplandetail',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='客户'),
        ),
    ]
