# Generated by Django 4.2.30 on 2026-04-30 07:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_add_plan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplandetail',
            name='cloth_color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='用布颜色'),
        ),
        migrations.AddField(
            model_name='productionplandetail',
            name='cloth_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='余料数量'),
        ),
        migrations.AddField(
            model_name='productionplandetail',
            name='cloth_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='用布数量'),
        ),
    ]
