# Generated by Django 4.2.30 on 2026-05-03 05:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def _backfill_dyeing_received(apps, schema_editor):
    DyeingOrder = apps.get_model('production', 'DyeingOrder')
    zero = Decimal('0')
    for o in DyeingOrder.objects.filter(status='completed'):
        rq = o.received_quantity or zero
        if rq == zero and o.quantity:
            o.received_quantity = o.quantity
            o.save(update_fields=['received_quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_add_cloth_usage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeavingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=100, verbose_name='布料名称')),
                ('fabric_color', models.CharField(blank=True, default='', max_length=50, verbose_name='颜色')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='约定产量')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='已到货数量')),
                ('unit', models.CharField(default='米', max_length=10, verbose_name='单位')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='预计交期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('receiving', '到货中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.warehousenode', verbose_name='入库仓')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_weaving_order', to='production.material', verbose_name='汇总坯布库存行')),
            ],
            options={
                'verbose_name': '布厂外协单',
                'verbose_name_plural': '布厂外协单',
            },
        ),
        migrations.AddField(
            model_name='dyeingorder',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='已到货数量'),
        ),
        migrations.AlterField(
            model_name='dyeingorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='约定产量'),
        ),
        migrations.AlterField(
            model_name='dyeingorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('receiving', '到货中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('辅料', '辅料'), ('坯布', '坯布'), ('染厂', '染厂'), ('布厂', '布厂')], max_length=10, verbose_name='供应商类型'),
        ),
        migrations.CreateModel(
            name='WeavingReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本批到货米数')),
                ('receipt_date', models.DateField(verbose_name='到货日期')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.weavingorder', verbose_name='布厂单')),
            ],
            options={
                'verbose_name': '布厂到货记录',
                'verbose_name_plural': '布厂到货记录',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='weavingorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weaving_orders', to='production.supplier', verbose_name='布厂'),
        ),
        migrations.CreateModel(
            name='DyeingReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本批到货米数')),
                ('receipt_date', models.DateField(verbose_name='到货日期')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.dyeingorder', verbose_name='染色单')),
            ],
            options={
                'verbose_name': '染色到货记录',
                'verbose_name_plural': '染色到货记录',
                'ordering': ['-id'],
            },
        ),
        migrations.RunPython(_backfill_dyeing_received, migrations.RunPython.noop),
    ]
