# Generated by Django 4.2.30 on 2026-05-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_template_product_and_drop_finished_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', '草稿'),
                    ('completed', '已完成'),
                    ('cancelled', '已取消'),
                    ('reversed', '已冲销'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
    ]
